import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '/client/img2threejs/runtime/geometry_kit.js';
const { addMesh, addSocket, measureModelPerformance } = createGeometryKit(THREE);
const V=(x,y,z)=>new THREE.Vector3(x,y,z);
function mats(){const cloth=(c)=>new THREE.MeshPhysicalMaterial({color:c,roughness:.72,metalness:.12,clearcoat:.2});return {red:cloth(0x7b1f24),redHi:cloth(0xb63a32),black:cloth(0x17171b),gold:new THREE.MeshPhysicalMaterial({color:0xb99152,metalness:.88,roughness:.25}),skin:cloth(0xd18c72),hair:cloth(0x1b1718),wood:cloth(0x4b211d),glow:new THREE.MeshBasicMaterial({color:0xff8b3d})};}
function mesh(p,g,m,n,pos,scale){const o=addMesh(p,g,m,n,pos);if(scale)o.scale.fromArray(scale);return o;}
function tube(p,a,b,r,m,n){const d=b.clone().sub(a),g=new THREE.CylinderGeometry(r,r,d.length(),12);const o=mesh(p,g,m,n,a.toArray());o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return o;}
function pivot(root,name,pos){const p=new THREE.Group();p.name=name;p.position.fromArray(pos);p.userData.semanticPivot=name;root.add(p);return p;}
function buildBody(root,m){
 const pelvis=pivot(root,'pivot_pelvis',[0,1.25,0]);mesh(pelvis,new THREE.CylinderGeometry(.54,.7,.34,16),m.black,'kimono_pelvis',[0,0,0]);
 const torso=pivot(root,'pivot_torso',[0,1.62,0]);mesh(torso,new THREE.CapsuleGeometry(.55,.9,8,20),m.black,'sentinel_torso',[0,.55,0],[1.08,1.12,.7]);mesh(torso,new THREE.BoxGeometry(.9,1.1,.07),m.red,'front_kimono_panel',[0,.48,.38],[1,.92,1]);
 for(let i=-2;i<=2;i++){mesh(torso,new THREE.BoxGeometry(.11,.9,.08),m.gold,`front_seam_${i}`,[i*.2,.52,.44],[1,1,1]);}
 mesh(torso,new THREE.TorusGeometry(.44,.055,8,24),m.redHi,'obi_belt',[0,.1,.08],[1.3,1,.8]); mesh(torso,new THREE.CylinderGeometry(.15,.15,.18,12),m.gold,'crest',[0,.72,.46],[1,1,.25]);
 const head=pivot(root,'pivot_head',[0,3.03,0]);mesh(head,new THREE.SphereGeometry(.4,24,18),m.skin,'face',[0,.18,.05],[.9,1.08,.86]);mesh(head,new THREE.SphereGeometry(.47,24,16),m.hair,'hair',[0,.3,-.02],[1.03,1.1,.9]);mesh(head,new THREE.CylinderGeometry(.15,.15,.2,12),m.hair,'bun',[0,.72,-.03]);
 for(const side of [-1,1]){const s=side<0?'left':'right',sh=pivot(root,`pivot_${s}_shoulder`,[side*.62,2.28,0]);mesh(sh,new THREE.BoxGeometry(.38,.18,.48),m.redHi,`${s}_lamellar_guard`,[0,0,.06],[1,1.3,1]);for(let j=0;j<4;j++)mesh(sh,new THREE.BoxGeometry(.3,.1,.42),m.gold,`${s}_lamella_${j}`,[0,-.08-j*.11,.08]);const arm=pivot(root,`pivot_${s}_arm`,[side*.68,2.04,0]);tube(arm,V(0,.12,0),V(side*.08,-.72,.03),.18,m.black,`${s}_sleeve`);mesh(arm,new THREE.SphereGeometry(.17,16,12),m.skin,`${s}_hand`,[side*.08,-.86,.1]);}
 for(const side of [-1,1]){const s=side<0?'left':'right',leg=pivot(root,`pivot_${s}_leg`,[side*.28,.92,0]);mesh(leg,new THREE.CapsuleGeometry(.16,.56,8,12),m.black,`${s}_leg`);mesh(leg,new THREE.BoxGeometry(.36,.18,.6),m.wood,`${s}_geta`,[0,-.36,.1],[1,1,.85]);mesh(leg,new THREE.BoxGeometry(.42,.06,.7),m.gold,`${s}_geta_trim`,[0,-.26,.1]);}
 const coat=pivot(root,'pivot_coat',[0,1.5,-.02]);mesh(coat,new THREE.ConeGeometry(.96,1.35,12),m.black,'tapered_coat',[0,.18,0],[1,.9,.74]);
}
function buildUmbrella(root,m){const u=pivot(root,'pivot_weapon_primary',[1.15,1.52,.04]);tube(u,V(0,-.72,0),V(0,1.45,0),.055,m.gold,'umbrella_staff');mesh(u,new THREE.ConeGeometry(1.03,.35,20),m.red,'umbrella_canopy',[0,1.55,0],[1,1,.72]);mesh(u,new THREE.CylinderGeometry(.2,.2,.1,16),m.gold,'canopy_cap',[0,1.76,0]);for(let i=0;i<12;i++){const a=i*Math.PI*2/12; tube(u,V(0,1.72,0),V(Math.cos(a)*.95,1.5,Math.sin(a)*.68),.018,m.gold,`umbrella_rib_${i}`);}mesh(u,new THREE.CylinderGeometry(.13,.13,.3,12),m.black,'grip',[0,-.82,0]);mesh(u,new THREE.TorusGeometry(.11,.025,8,18),m.redHi,'grip_ring',[0,-.98,0]);}
 export function createKarakasaPlayableHeroModel(options={}){const root=new THREE.Group();root.name='karakasa_playable_hero';root.userData.heroId='karakasa';const m=mats();buildBody(root,m);buildUmbrella(root,m);const pivots={root:root.name,head:'pivot_head',torso:'pivot_torso',pelvis:'pivot_pelvis',leftShoulder:'pivot_left_shoulder',rightShoulder:'pivot_right_shoulder',leftArm:'pivot_left_arm',rightArm:'pivot_right_arm',leftLeg:'pivot_left_leg',rightLeg:'pivot_right_leg'};const sockets={weapon_primary:'socket_weapon_primary',hand_off:'socket_hand_off',back_accessory:'socket_back_accessory',vfx_origin:'socket_vfx_origin'};addSocket(root,sockets.weapon_primary,[1.15,1.75,.18]);addSocket(root,sockets.hand_off,[-.72,1.3,.18]);addSocket(root,sockets.back_accessory,[0,2.5,-.34]);addSocket(root,sockets.vfx_origin,[0,2.1,.18]);const colliderHints={capsule:{type:'capsule',radius:.6,height:2.7,center:[0,1.5,0]},head:{type:'sphere',radius:.43,center:[0,3.2,0]},umbrella:{type:'capsule',radius:.38,height:2.3,center:[1.15,1.5,0]}};root.userData.characterModel={schemaVersion:'1.0.0',heroId:'karakasa',implementation:'procedural-umbrella-sentinel',coordinateSystem:'three-y-up-front-positive-z',pivots,sockets,colliderHints,performance:{...measureModelPerformance(root),lod0TriangleBudget:30000,mobileDrawCallBudget:26},animation:{mode:'procedural-pivots',locomotion:['idle','walk','run','air','death'],combat:['fire','shield']}};root.userData.sculptRuntime={targetName:'Karakasa Umbrella Sentinel',pivots,sockets,colliderHints};root.traverse(o=>{if(o.isMesh){o.castShadow=options.castShadow??true;o.receiveShadow=options.receiveShadow??true;}});root.updateMatrixWorld(true);return root;}
 export function createKarakasaPlayableHeroLookDevLights(){const g=new THREE.Group();g.add(new THREE.HemisphereLight(0xffd5cb,0x11151d,1.65));const k=new THREE.DirectionalLight(0xffe0b0,3.3);k.position.set(-3,6,5);k.castShadow=true;g.add(k);const r=new THREE.DirectionalLight(0x6488ff,2.1);r.position.set(4,3,-4);g.add(r);return g;}
