import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '../runtime/geometry_kit.js';
const { addMesh, addTube, addTaperedTube, addRivet, addSocket, measureModelPerformance } = createGeometryKit(THREE);
const mat=(color,roughness=.46,metalness=.18,emissive=0)=>new THREE.MeshPhysicalMaterial({color,roughness,metalness,clearcoat:.24,emissive,emissiveIntensity:emissive?1.8:0});
function mats(){return {pink:mat(0xd75e8e,.4,.12),cream:mat(0xf3c4cf,.55,.08),gun:mat(0x4e5660,.3,.72),dark:mat(0x282d36,.62,.56),glow:mat(0x91d6ff,.16,.2,0x318dcc)};}
function petal(parent,i,m){const a=i*Math.PI*2/8; const x=Math.cos(a)*.48,z=.34+Math.sin(a)*.48; addMesh(parent,new THREE.CapsuleGeometry(.14,.55,8,14),m.pink,`petal_${i}`,[x,3.62,z],[0,a*.35, a],[.8,1.15,.4]);}
export function createBotanPlayableHeroModel(options={}){
 const root=new THREE.Group();root.name='botan_playable_hero';root.userData.heroId='botan';const m=mats();
 const torso=new THREE.Group();torso.name='pivot_torso';torso.userData.semanticPivot='torso';root.add(torso); addMesh(torso,new THREE.CylinderGeometry(.72,.9,1.2,24),m.gun,'cylindrical_shell_torso',[0,2.2,0]); addMesh(torso,new THREE.TorusGeometry(.76,.09,12,24),m.pink,'shell_rim',[0,2.78,0],[0,0,0]); addMesh(torso,new THREE.SphereGeometry(.34,24,16),m.glow,'central_optic',[0,2.55,.68],[0,0,0],[1,1,.35]);
 const head=new THREE.Group();head.name='pivot_head';head.userData.semanticPivot='head';root.add(head);addMesh(head,new THREE.SphereGeometry(.34,24,16),m.dark,'optic_housing',[0,3.52,.18]);addMesh(head,new THREE.SphereGeometry(.13,16,12),m.glow,'optic_lens',[0,3.52,.48]); for(let i=0;i<8;i++)petal(head,i,m);
 function arm(side){const s=side==='left'?-1:1;const g=new THREE.Group();g.name=`pivot_${side}_arm`;g.userData.semanticPivot=`${side}_arm`;root.add(g);addTaperedTube(g,`${side}_recoil_arm`,[s*.67,2.48,.02],[s*1.05,1.88,.32],.22,.18,m.dark,14);addMesh(g,new THREE.CylinderGeometry(.2,.24,.58,16),m.gun,`${side}_braced_forearm`,[s*1.12,1.62,.4],[0,0,s*.7]);addMesh(g,new THREE.BoxGeometry(.34,.22,.45),m.cream,`${side}_brace_plate`,[s*1.12,1.84,.45]);addSocket(g,`socket_${side}_hand`,[s*1.12,1.35,.55]);}
 arm('left');arm('right');
 const pelvis=new THREE.Group();pelvis.name='pivot_pelvis';pelvis.userData.semanticPivot='pelvis';root.add(pelvis);addMesh(pelvis,new THREE.SphereGeometry(.62,24,16),m.pink,'flared_hip_core',[0,1.38,0],[0,0,0],[1.2,.65,1]);
 function leg(side,angle){const s=side==='left'?-1:1;const g=new THREE.Group();g.name=`pivot_${side}_leg`;g.userData.semanticPivot=`${side}_leg`;root.add(g);addTaperedTube(g,`${side}_tripod_leg`,[s*.35,1.2,0],[s*.68,.24,.18],.27,.18,m.dark,14);addMesh(g,new THREE.BoxGeometry(.5,.16,.72),m.gun,`${side}_planted_foot`,[s*.72,.1,.28],[0,angle,0]);addTube(g,`${side}_foot_trim`,[s*.52,.18,.42],[s*.92,.18,.42],.03,m.cream,8);}
 leg('left',-.1);leg('right',.1);
 const weapon=new THREE.Group();weapon.name='pivot_weapon_primary';weapon.userData.semanticPivot='weapon_primary';root.add(weapon);addMesh(weapon,new THREE.CylinderGeometry(.24,.32,.9,20),m.gun,'bloom_cannon',[0,2.34,1.03],[Math.PI/2,0,0]);addMesh(weapon,new THREE.TorusGeometry(.31,.06,10,20),m.pink,'cannon_flower_ring',[0,2.34,1.5],[Math.PI/2,0,0]);addSocket(weapon,'socket_muzzle_vfx',[0,2.34,1.72]);
 const fins=new THREE.Group();fins.name='pivot_back_accessory';fins.userData.semanticPivot='back_accessory';root.add(fins);for(let i=0;i<6;i++){const a=i*Math.PI/3;addMesh(fins,new THREE.BoxGeometry(.12,.7,.08),m.cream,`petal_heat_fin_${i}`,[Math.cos(a)*.9,2.55,Math.sin(a)*.9],[0,a,0],[1,1,.4]);}
 addSocket(root,'socket_hand_off',[-1.12,1.35,.55]);addSocket(root,'socket_back_accessory',[0,2.55,-.85]);addSocket(root,'socket_vfx_origin',[0,2.4,.7]);
 const pivots={root:root.name,head:head.name,torso:torso.name,pelvis:pelvis.name,leftShoulder:'pivot_left_arm',rightShoulder:'pivot_right_arm',leftArm:'pivot_left_arm',rightArm:'pivot_right_arm',leftLeg:'pivot_left_leg',rightLeg:'pivot_right_leg'};const sockets={weapon_primary:'socket_muzzle_vfx',hand_off:'socket_hand_off',back_accessory:'socket_back_accessory',vfx_origin:'socket_vfx_origin'};const colliderHints={body:{type:'capsule',radius:.82,height:3.1},head:{type:'sphere',radius:.4},weapon:{type:'capsule',radius:.3,height:1.1},accessory:{type:'box',size:[2,.8,2]}};const performance=measureModelPerformance(root);performance.lod0TriangleBudget=30000;performance.mobileDrawCallBudget=36;root.userData.characterModel={schemaVersion:'1.0.0',heroId:'botan',implementation:'handcrafted-img2threejs',coordinateSystem:'three-y-up-front-positive-z',pivots,sockets,colliderHints,performance,optimization:{strategy:'semantic-pivot compaction',preservedAnchors:Object.values(sockets)},palette:['#d75e8e','#f3c4cf','#4e5660']};root.userData.sculptRuntime={pivots,sockets,colliderHints};root.traverse(o=>{if(o.isMesh){o.castShadow=options.castShadow??true;o.receiveShadow=options.receiveShadow??true;}});return root;
}
export function createBotanPlayableHeroLookDevLights(){const g=new THREE.Group();g.name='botan_lights';g.add(new THREE.HemisphereLight(0xffe0ed,0x222733,1.55));const k=new THREE.DirectionalLight(0xfff0f5,3);k.position.set(-3,6,5);g.add(k);const r=new THREE.DirectionalLight(0x76a9e8,2);r.position.set(3,3,-4);g.add(r);return g;}
