import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '/client/img2threejs/runtime/geometry_kit.js';
const { addMesh, addSocket, rebasePivot, measureModelPerformance } = createGeometryKit(THREE);
const black=new THREE.MeshStandardMaterial({color:0x111827,roughness:.55,metalness:.15}), blue=new THREE.MeshStandardMaterial({color:0x24517a,roughness:.4,metalness:.25}), belly=new THREE.MeshStandardMaterial({color:0xd6dde4,roughness:.8}), orange=new THREE.MeshStandardMaterial({color:0xd36b32,roughness:.45}), silver=new THREE.MeshStandardMaterial({color:0xaab8c5,roughness:.25,metalness:.8});
function mesh(p,g,m,n,pos,scale=[1,1,1]){const x=addMesh(p,g,m,n,pos);x.scale.set(...scale);return x;}function tube(p,n,a,b,r,m){const d=new THREE.Vector3(...b).sub(new THREE.Vector3(...a));const x=mesh(p,new THREE.CylinderGeometry(r,r,d.length(),8),m,n,new THREE.Vector3(...a).add(new THREE.Vector3(...b)).multiplyScalar(.5).toArray());x.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return x;}function pivot(root,key,pos){const g=new THREE.Group();g.name=`pivot_${key}`;g.userData.pivotRestPosition=[...pos];root.add(g);return g;}
function create(){const root=new THREE.Group();root.name='tsubakuro_playable_hero';root.userData.heroId='tsubakuro';
 const torso=pivot(root,'torso',[0,1.9,0]);mesh(torso,new THREE.CapsuleGeometry(.43,.7,8,16),black,'torso_blackcoat',[0,1.9,0],[1.12,1,.72]);mesh(torso,new THREE.SphereGeometry(.4,16,10),belly,'belly_panel',[0,1.98,.3],[.88,.9,.34]);mesh(torso,new THREE.BoxGeometry(.06,.5,.06),silver,'coat_clasp',[0,2.1,.62]);
 const pelvis=pivot(root,'pelvis',[0,1.28,0]);mesh(pelvis,new THREE.SphereGeometry(.4,14,10),black,'pelvis',[0,1.28,0],[1.1,.52,.75]);
 const head=pivot(root,'head',[0,2.85,0]);mesh(head,new THREE.SphereGeometry(.34,18,12),black,'head',[0,2.96,.02],[1,.98,.9]);mesh(head,new THREE.ConeGeometry(.14,.5,10),orange,'beak',[0,2.94,.38],[1,.7,1]);for(const [n,x] of [['eye_l',-.14],['eye_r',.14]])mesh(head,new THREE.SphereGeometry(.05,10,8),silver,n,[x,3.08,.29]);
 const shL=pivot(root,'shoulder_l',[-.5,2.4,0]), shR=pivot(root,'shoulder_r',[.5,2.4,0]);const armL=pivot(root,'arm_l',[-.62,2.08,0]), armR=pivot(root,'arm_r',[.62,2.08,0]);for(const [a,sgn,s] of [[armL,-1,'l'],[armR,1,'r']]){tube(a,`arm_${s}`, [sgn*.62,2.3,0],[sgn*.85,1.75,.08],.12,black);mesh(a,new THREE.SphereGeometry(.14,10,8),orange,`talon_${s}`,[sgn*.85,1.66,.15],[1,.7,1]);}
 const legL=pivot(root,'leg_l',[-.23,1.15,0]),legR=pivot(root,'leg_r',[.23,1.15,0]);for(const [g,sgn,s] of [[legL,-1,'l'],[legR,1,'r']]){tube(g,`leg_${s}`,[sgn*.23,1.2,0],[sgn*.27,.45,.03],.15,black);mesh(g,new THREE.CapsuleGeometry(.16,.34,6,10),orange,`foot_${s}`,[sgn*.27,.2,.2],[1,.5,1.45]);}
 // Swallow silhouette: sharply swept blue-black wings and split tail streamers.
 for(const [s,sgn] of [['l',-1],['r',1]]){const w=pivot(root,`wing_${s}`,[sgn*.4,2.25,-.05]);mesh(w,new THREE.ConeGeometry(.3,1.5,5),blue,`wing_${s}_primary`,[sgn*1.05,2.55,-.18],[.58,1.05,.25]);mesh(w,new THREE.ConeGeometry(.24,1.05,5),black,`wing_${s}_secondary`,[sgn*.82,2.1,-.12],[.55,1,.22]);}
 const tail=pivot(root,'tail',[0,1.55,-.2]);for(const sgn of [-1,1]){tube(tail,`tail_${sgn<0?'l':'r'}`,[0,1.6,-.2],[sgn*.4,.72,-.82],.08,blue);mesh(tail,new THREE.ConeGeometry(.13,.45,5),blue,`tail_fan_${sgn<0?'l':'r'}`,[sgn*.4,.62,-.88],[1,.9,.28]);}
 const blade=pivot(root,'blade',[-.92,1.9,.2]);mesh(blade,new THREE.BoxGeometry(.08,1.2,.08),silver,'dagger_grip',[0,0,0]);mesh(blade,new THREE.ConeGeometry(.09,.7,4),silver,'dagger_blade',[0,.9,0],[1,1,.35]);addSocket(blade,'socket_weapon_primary',[0,1.25,.04]);addSocket(armR,'socket_hand_off',[0,0,.16]);addSocket(root,'socket_back_accessory',[0,2.1,-.4]);addSocket(root,'socket_vfx_origin',[0,1.9,.4]);
 const pivots={root:root.name,head:head.name,torso:torso.name,pelvis:pelvis.name,leftShoulder:shL.name,rightShoulder:shR.name,leftArm:armL.name,rightArm:armR.name,leftLeg:legL.name,rightLeg:legR.name,shoulder_l:shL.name,shoulder_r:shR.name,arm_l:armL.name,arm_r:armR.name,leg_l:legL.name,leg_r:legR.name};const sockets={weapon_primary:'socket_weapon_primary',hand_off:'socket_hand_off',back_accessory:'socket_back_accessory',vfx_origin:'socket_vfx_origin'};root.userData.characterModel={schemaVersion:'1.0.0',heroId:'tsubakuro',implementation:'handcrafted-img2threejs',coordinateSystem:'three-y-up-front-positive-z',pivots,sockets,colliderHints:{torso:{type:'capsule',radius:.5,height:1.65},head:{type:'sphere',radius:.34},height:3.35},performance:{...measureModelPerformance(root),lod0TriangleBudget:45000,mobileDrawCallBudget:24}};root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return root;}
export function createTsubakuroPlayableHeroModel(options={}){return create(options);}
