import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '/client/img2threejs/runtime/geometry_kit.js';
const { addMesh, addSocket, rebasePivot, measureModelPerformance } = createGeometryKit(THREE);
const M={feather:new THREE.MeshStandardMaterial({color:0xd7e4e7,roughness:.78}),blue:new THREE.MeshStandardMaterial({color:0x2f6fa8,roughness:.56,metalness:.12}),red:new THREE.MeshStandardMaterial({color:0xd4525d,roughness:.48}),gold:new THREE.MeshStandardMaterial({color:0xd4b458,metalness:.62,roughness:.28}),dark:new THREE.MeshStandardMaterial({color:0x1c2834,metalness:.25,roughness:.3}),cyan:new THREE.MeshStandardMaterial({color:0x67dbe2,emissive:0x123d4a,emissiveIntensity:1.2,roughness:.25})};
const mesh=(p,g,m,n,pos,scale=[1,1,1])=>{const x=addMesh(p,g,m,n,pos);x.scale.set(...scale);return x;};
const tube=(p,n,a,b,r,m)=>{const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),d=B.clone().sub(A);const mid=A.clone().add(B).multiplyScalar(.5);const x=mesh(p,new THREE.CylinderGeometry(r,r,d.length(),8),m,n,[mid.x,mid.y,mid.z]);x.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return x;};
function pivot(root,key,pos){const p=new THREE.Group();p.name=`pivot_${key}`;p.userData.semanticPivot=key;root.add(p);root.updateMatrixWorld(true);rebasePivot(p,pos);return p;}
function create(){const root=new THREE.Group();root.name='hibari_playable_hero';root.userData.heroId='hibari';
 const torso=pivot(root,'torso',[0,2.0,0]);mesh(torso,new THREE.CapsuleGeometry(.45,.74,8,16),M.blue,'torso_messenger_vest',[0,2.03,0],[1.02,1,.68]);mesh(torso,new THREE.BoxGeometry(.2,.7,.1),M.red,'torso_scarf_center',[0,2.1,.44]);
 const pelvis=pivot(root,'pelvis',[0,1.33,0]);mesh(pelvis,new THREE.SphereGeometry(.43,16,10),M.dark,'pelvis_satchel',[0,1.35,0],[1.1,.54,.82]);
 const head=pivot(root,'head',[0,3.0,0]);mesh(head,new THREE.SphereGeometry(.35,20,14),M.feather,'head',[0,3.05,0],[.92,1.1,.9]);mesh(head,new THREE.ConeGeometry(.11,.42,10),M.gold,'beak',[0,3.03,.36],[1,.72,1]);mesh(head,new THREE.SphereGeometry(.05,10,8),M.dark,'eye_l',[-.14,3.12,.28]);mesh(head,new THREE.SphereGeometry(.05,10,8),M.dark,'eye_r',[.14,3.12,.28]);
 const shL=pivot(root,'shoulder_l',[-.5,2.4,0]),shR=pivot(root,'shoulder_r',[.5,2.4,0]);mesh(shL,new THREE.SphereGeometry(.23,12,8),M.blue,'shoulder_l',[-.5,2.4,0],[1,.8,.8]);mesh(shR,new THREE.SphereGeometry(.23,12,8),M.blue,'shoulder_r',[.5,2.4,0],[1,.8,.8]);
 const armL=pivot(root,'arm_l',[-.63,2.12,0]),armR=pivot(root,'arm_r',[.63,2.12,0]);tube(armL,'arm_l',[-.62,2.3,0],[-.82,1.73,.06],.13,M.feather);tube(armR,'arm_r',[.62,2.3,0],[.82,1.73,.06],.13,M.feather);mesh(armL,new THREE.SphereGeometry(.13,10,8),M.gold,'hand_l',[-.82,1.68,.1]);mesh(armR,new THREE.SphereGeometry(.13,10,8),M.gold,'hand_r',[.82,1.68,.1]);
 const legL=pivot(root,'leg_l',[-.24,1.17,0]),legR=pivot(root,'leg_r',[.24,1.17,0]);tube(legL,'leg_l',[-.24,1.18,0],[-.28,.42,.08],.16,M.blue);tube(legR,'leg_r',[.24,1.18,0],[.28,.42,.08],.16,M.blue);mesh(legL,new THREE.CapsuleGeometry(.19,.34,7,12),M.gold,'foot_l',[-.28,.17,.2],[1,.5,1.4]);mesh(legR,new THREE.CapsuleGeometry(.19,.34,7,12),M.gold,'foot_r',[.28,.17,.2],[1,.5,1.4]);
 // Swift messenger identity: swept wings, crest, and dispatch tube.
 for(const s of [-1,1]){const wing=pivot(root,s<0?'wing_l':'wing_r',[s*.4,2.36,-.02]);for(let i=0;i<5;i++)mesh(wing,new THREE.ConeGeometry(.2,.92-i*.1,6),i===0?M.red:(i%2?M.feather:M.blue),`wing_${s<0?'l':'r'}_primary_${i}`,[s*(.7+i*.12),2.4-i*.14,-.14-i*.04],[.55,1,.26]);}
 const crest=pivot(root,'crest',[0,3.34,-.02]);for(let i=0;i<3;i++)mesh(crest,new THREE.ConeGeometry(.08,.4,8),M.red,`crest_feather_${i}`,[(-.16+i*.16),3.5+Math.abs(i-1)*.04,-.08],[1,.8,1]);
 const satchel=pivot(root,'satchel',[-.72,1.95,.12]);mesh(satchel,new THREE.BoxGeometry(.42,.52,.18),M.red,'dispatch_satchel',[0,0,0],[1,.9,.7]);tube(satchel,'satchel_strap',[0,.2,0],[.3,.75,0],.035,M.gold);addSocket(satchel,'socket_weapon_primary',[0,.18,.2]);
 addSocket(armL,'socket_hand_off',[0,0,.15]);addSocket(root,'socket_back_accessory',[0,2.45,-.34]);addSocket(root,'socket_vfx_origin',[0,2.0,.46]);
 const pivots={root:root.name,head:head.name,torso:torso.name,pelvis:pelvis.name,shoulder_l:shL.name,shoulder_r:shR.name,arm_l:armL.name,arm_r:armR.name,leg_l:legL.name,leg_r:legR.name,leftShoulder:shL.name,rightShoulder:shR.name,leftArm:armL.name,rightArm:armR.name,leftLeg:legL.name,rightLeg:legR.name};const sockets={weapon_primary:'socket_weapon_primary',hand_off:'socket_hand_off',back_accessory:'socket_back_accessory',vfx_origin:'socket_vfx_origin'};
 root.userData.characterModel={schemaVersion:'1.0.0',heroId:'hibari',implementation:'handcrafted-img2threejs',coordinateSystem:'three-y-up-front-positive-z',pivots,sockets,colliderHints:{torso:{type:'capsule',radius:.53,height:1.68},head:{type:'sphere',radius:.36},height:3.72},performance:{...measureModelPerformance(root),lod0TriangleBudget:45000,mobileDrawCallBudget:24}};root.userData.sculptRuntime={pivots,sockets};root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return root;}
export function createHibariPlayableHeroModel(options={}){return create(options);}
