import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '../runtime/geometry_kit.js';

const { addMesh, addSocket, measureModelPerformance } = createGeometryKit(THREE);
const mat = (color, metalness = 0.25, roughness = 0.55) => new THREE.MeshStandardMaterial({ color, metalness, roughness });
const M = { sand: mat(0x8f7b4f, .72, .36), slate: mat(0x4c5154, .65, .44), linen: mat(0xc7b58a, .05, .8), dark: mat(0x171a1b, .45, .62), skin: mat(0xb88468, .05, .72), glow: new THREE.MeshStandardMaterial({ color: 0xc7b58a, emissive: 0x6b5426, emissiveIntensity: 1.8 }) };
const mesh = (p, g, m, name, pos, scale = [1, 1, 1], rot = [0, 0, 0]) => { const o = addMesh(p, g, m, name, pos); o.scale.fromArray(scale); o.rotation.fromArray(rot); return o; };
const box = (p, m, name, pos, size, rot = [0, 0, 0]) => mesh(p, new THREE.BoxGeometry(...size), m, name, pos, [1, 1, 1], rot);
const cyl = (p, m, name, pos, radius, depth, rot = [0, 0, 0]) => mesh(p, new THREE.CylinderGeometry(radius, radius * 1.08, depth, 16), m, name, pos, [1, 1, 1], rot);
function limb(root, side, y, m) { const s = side === 'l' ? -1 : 1; const sh = new THREE.Group(); sh.name = `pivot_shoulder_${side}`; root.add(sh); mesh(sh, new THREE.SphereGeometry(.23, 16, 12), m, `shoulder_${side}_plate`, [s * .58, y, 0], [1.25, .7, 1.0]); const arm = new THREE.Group(); arm.name = `pivot_arm_${side}`; root.add(arm); mesh(arm, new THREE.CapsuleGeometry(.17, .48, 8, 14), M.dark, `arm_${side}_under`, [s * .68, 2.2, .02], [1, 1.1, 1]); mesh(arm, new THREE.BoxGeometry(.28, .52, .34), M.sand, `arm_${side}_gauntlet`, [s * .72, 1.92, .08]); const leg = new THREE.Group(); leg.name = `pivot_leg_${side}`; root.add(leg); mesh(leg, new THREE.CapsuleGeometry(.2, .55, 8, 14), M.dark, `leg_${side}_under`, [s * .28, 1.1, 0]); box(leg, M.sand, `leg_${side}_greave`, [s * .28, .78, .08], [.4, .5, .42]); box(leg, M.slate, `boot_${side}_square`, [s * .28, .22, .16], [.54, .28, .7]); }
export function createSedoraPlayableHeroModel(options = {}) {
  const root = new THREE.Group(); root.name = 'sedora_playable_hero'; root.userData.heroId = 'sedora';
  const pelvis = new THREE.Group(); pelvis.name = 'pivot_pelvis'; root.add(pelvis); box(pelvis, M.dark, 'pelvis_underlayer', [0, 1.55, 0], [1.0, .45, .62]); box(pelvis, M.sand, 'pelvis_armor_belt', [0, 1.72, .12], [1.15, .28, .76]);
  const torso = new THREE.Group(); torso.name = 'pivot_torso'; root.add(torso); mesh(torso, new THREE.CapsuleGeometry(.55, .65, 10, 20), M.dark, 'torso_underlayer', [0, 2.5, 0], [1.15, 1.1, .75]); box(torso, M.sand, 'layered_stone_cuirass', [0, 2.7, .16], [1.18, .9, .62]); box(torso, M.slate, 'cuirass_lower_plate', [0, 2.25, .2], [.84, .26, .5]); cyl(torso, M.linen, 'cuirass_emblem', [0, 2.74, .49], .12, .035, [Math.PI / 2, 0, 0]);
  const head = new THREE.Group(); head.name = 'pivot_head'; root.add(head); mesh(head, new THREE.SphereGeometry(.32, 20, 14), M.skin, 'head_face', [0, 3.35, .08], [1, 1.15, .82]); box(head, M.sand, 'slab_visor', [0, 3.43, .36], [.62, .3, .2]); box(head, M.slate, 'visor_sight', [0, 3.42, .47], [.38, .08, .05]); box(head, M.sand, 'visor_fin_l', [-.43, 3.46, 0], [.18, .35, .35], [0, 0, -.15]); box(head, M.sand, 'visor_fin_r', [.43, 3.46, 0], [.18, .35, .35], [0, 0, .15]);
  limb(root, 'l', 2.85, M.sand); limb(root, 'r', 2.85, M.sand);
  const shield = new THREE.Group(); shield.name = 'pivot_back_shield'; root.add(shield); box(shield, M.sand, 'escort_shield_core', [0, 2.55, -.48], [1.48, 2.3, .22]); box(shield, M.slate, 'escort_shield_inner', [0, 2.55, -.62], [1.18, 1.92, .08]); for (const x of [-.55, .55]) for (const y of [1.75, 2.55, 3.35]) cyl(shield, M.linen, `shield_rivet_${x}_${y}`, [x, y, -.72], .035, .04, [Math.PI / 2, 0, 0]);
  const weapon = new THREE.Group(); weapon.name = 'pivot_pile_driver'; root.add(weapon); cyl(weapon, M.dark, 'pile_driver_handle', [.86, 1.25, .32], .09, 1.8, [0, 0, -0.25]); cyl(weapon, M.sand, 'pile_driver_head', [.63, .35, .42], .22, .5, [0, 0, Math.PI / 2]); for (const x of [.52, .66, .8]) mesh(weapon, new THREE.ConeGeometry(.08, .42, 12), M.slate, `pile_driver_spike_${x}`, [x, .05, .42], [1, 1, 1], [0, 0, 0]); addSocket(weapon, 'socket_weapon_primary', [.86, .32, .4]);
  addSocket(root, 'socket_weapon_primary', [.86, .3, .4]); addSocket(root, 'socket_hand_off', [-.8, 1.95, .2]); addSocket(root, 'socket_back_accessory', [0, 2.7, -.7]); addSocket(root, 'socket_vfx_origin', [0, 2.3, .5]);
  const pivots = { root: root.name, head: head.name, torso: torso.name, pelvis: pelvis.name, leftShoulder: 'pivot_shoulder_l', rightShoulder: 'pivot_shoulder_r', leftArm: 'pivot_arm_l', rightArm: 'pivot_arm_r', leftLeg: 'pivot_leg_l', rightLeg: 'pivot_leg_r', shoulder_l: 'pivot_shoulder_l', shoulder_r: 'pivot_shoulder_r', arm_l: 'pivot_arm_l', arm_r: 'pivot_arm_r', leg_l: 'pivot_leg_l', leg_r: 'pivot_leg_r' }; const sockets = { weapon_primary: 'socket_weapon_primary', hand_off: 'socket_hand_off', back_accessory: 'socket_back_accessory', vfx_origin: 'socket_vfx_origin' };
  const colliderHints = { torso: { type: 'capsule', radius: .62, height: 2.45 }, head: { type: 'sphere', radius: .34 }, shield: { type: 'box', size: [1.7, 2.5, .35] } }; root.userData.characterModel = { schemaVersion: '1.0.0', heroId: 'sedora', implementation: 'procedural-img2threejs', coordinateSystem: 'three-y-up-front-positive-z', pivots, sockets, colliderHints, performance: { ...measureModelPerformance(root), lod0TriangleBudget: 30000, mobileDrawCallBudget: 32 } }; root.userData.sculptRuntime = { pivots, sockets, colliderHints }; root.traverse(o => { if (o.isMesh) { o.castShadow = options.castShadow ?? true; o.receiveShadow = options.receiveShadow ?? true; } }); return root;
}
export function createSedoraPlayableHeroLookDevLights() { const g = new THREE.Group(); g.add(new THREE.HemisphereLight(0xd8e4ed, 0x1b2028, 1.5)); const k = new THREE.DirectionalLight(0xffdfb0, 3); k.position.set(-3, 6, 5); g.add(k); const r = new THREE.DirectionalLight(0x6fa8c9, 1.4); r.position.set(4, 3, -4); g.add(r); return g; }
