import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '/client/img2threejs/runtime/geometry_kit.js';
const { addMesh, addSocket, mergeStaticMeshesByMaterial, measureModelPerformance } = createGeometryKit(THREE);
const make=(c,metal=.5,rough=.42,em=0)=>new THREE.MeshStandardMaterial({color:c,metalness:metal,roughness:rough,emissive:em,emissiveIntensity:em?2.4:0});
const M={rust:make(0xc96d3d,.62,.4),charcoal:make(0x29252a,.8,.36),brass:make(0xd19a4a,.86,.24),glow:make(0xff7b18,.45,.2,0xff3b00),leather:make(0x4b1f20,.08,.86)};
const mesh=(p,g,m,n,pos=[0,0,0],s)=>{const x=addMesh(p,g,m,n,pos);if(s)x.scale.fromArray(s);return x;}; const limb=(p,n,x,y,z,r,h,m)=>mesh(p,new THREE.CapsuleGeometry(r,h,6,10),m,n,[x,y,z]);
function vent(p,x){for(let i=0;i<3;i++)mesh(p,new THREE.BoxGeometry(.08,.28,.05),M.glow,`heat_vent_${i}`,[x-.12+i*.12,2.35,.56]);}
function hammer(p){const h=new THREE.Group();h.name='forged_hammer';p.add(h);mesh(h,new THREE.CylinderGeometry(.1,.12,1.3,10),M.leather,'hammer_grip',[0,-.68,0]);mesh(h,new THREE.BoxGeometry(.75,.5,.55),M.charcoal,'hammer_block',[0,-1.42,0]);mesh(h,new THREE.BoxGeometry(.46,.12,.62),M.glow,'hammer_core',[0,-1.42,.31]);mesh(h,new THREE.CylinderGeometry(.14,.14,.2,12),M.brass,'hammer_cap',[0,-1.68,0]);return h;}
export function createBaragaPlayableHeroModel(options={}){
 const root=new THREE.Group();root.name='baraga_root';const pivots={root:root.name,head:'pivot_head',torso:'pivot_torso',pelvis:'pivot_pelvis',shoulder_l:'pivot_shoulder_l',shoulder_r:'pivot_shoulder_r',arm_l:'pivot_arm_l',arm_r:'pivot_arm_r',leg_l:'pivot_leg_l',leg_r:'pivot_leg_r',leftShoulder:'pivot_shoulder_l',rightShoulder:'pivot_shoulder_r',leftArm:'pivot_arm_l',rightArm:'pivot_arm_r',leftLeg:'pivot_leg_l',rightLeg:'pivot_leg_r'};
 const head=new THREE.Group();head.name=pivots.head;head.userData.semanticPivot='head';root.add(head);mesh(head,new THREE.BoxGeometry(.62,.48,.54),M.charcoal,'square_mask',[0,3.35,.03]);mesh(head,new THREE.BoxGeometry(.72,.1,.62),M.rust,'mask_brow',[0,3.56,.05]);for(const x of[-.34,.34]){mesh(head,new THREE.ConeGeometry(.14,.38,4),M.brass,`horn_block_${x}`, [x,3.72,.02],[1,1,1]);}mesh(head,new THREE.BoxGeometry(.38,.07,.06),M.glow,'mask_visor',[0,3.34,.31]);
 const torso=new THREE.Group();torso.name=pivots.torso;torso.userData.semanticPivot='torso';root.add(torso);mesh(torso,new THREE.BoxGeometry(1.16,1.02,.72),M.rust,'rectangular_forged_cuirass',[0,2.33,0]);mesh(torso,new THREE.BoxGeometry(.48,.48,.1),M.brass,'chest_medallion',[0,2.46,.4]);mesh(torso,new THREE.BoxGeometry(.09,.72,.08),M.charcoal,'center_girder',[0,2.3,.42]);vent(torso,-.42);vent(torso,.42);
 const pelvis=new THREE.Group();pelvis.name=pivots.pelvis;pelvis.userData.semanticPivot='pelvis';root.add(pelvis);mesh(pelvis,new THREE.BoxGeometry(1.05,.4,.7),M.charcoal,'pelvis_belt',[0,1.68,0]);mesh(pelvis,new THREE.BoxGeometry(.65,.1,.1),M.brass,'belt_buckle',[0,1.72,.4]);
 for(const side of[-1,1]){const s=side<0?'l':'r';const sh=new THREE.Group();sh.name=pivots[`shoulder_${s}`];sh.userData.semanticPivot=`shoulder_${s}`;root.add(sh);mesh(sh,new THREE.BoxGeometry(.5,.4,.64),M.rust,`horned_shoulder_${s}`,[side*.72,2.72,0]);mesh(sh,new THREE.ConeGeometry(.13,.3,4),M.brass,`shoulder_horn_${s}`,[side*.88,2.92,.04]);const arm=new THREE.Group();arm.name=pivots[`arm_${s}`];arm.userData.semanticPivot=`arm_${s}`;root.add(arm);limb(arm,`upper_arm_${s}`,side*.8,2.28,0,.22,.42,M.charcoal);mesh(arm,new THREE.CylinderGeometry(.27,.27,.42,10),M.brass,`piston_forearm_${s}`,[side*.82,1.78,.02]);mesh(arm,new THREE.CylinderGeometry(.12,.12,.22,10),M.glow,`piston_glow_${s}`,[side*.82,1.78,.25]);const leg=new THREE.Group();leg.name=pivots[`leg_${s}`];leg.userData.semanticPivot=`leg_${s}`;root.add(leg);limb(leg,`thick_thigh_${s}`,side*.32,1.2,0,.29,.46,M.charcoal);mesh(leg,new THREE.BoxGeometry(.5,.55,.62),M.rust,`braced_greave_${s}`,[side*.32,.58,.03]);mesh(leg,new THREE.BoxGeometry(.56,.18,.75),M.charcoal,`heavy_boot_${s}`,[side*.32,.16,.15]);}
 const weapon=addSocket(root,'socket_weapon_primary',[.96,1.74,.02]);const off=addSocket(root,'socket_hand_off',[-.88,1.76,.02]);const back=addSocket(root,'socket_back_accessory',[0,2.4,-.48]);const vfx=addSocket(root,'socket_vfx_origin',[0,2.4,.62]);const wh=hammer(weapon);wh.rotation.z=-.3;mesh(back,new THREE.CylinderGeometry(.32,.32,.9,12),M.brass,'back_heat_tank',[0,0,0],[1,1,.62]);mesh(back,new THREE.BoxGeometry(.6,.52,.12),M.rust,'tank_plate',[0,0,.32]);
 root.userData.characterModel={schemaVersion:'1.0.0',heroId:'baraga',implementation:'handcrafted-img2threejs',coordinateSystem:'three-y-up-front-positive-z',pivots,sockets:{weapon_primary:'socket_weapon_primary',hand_off:'socket_hand_off',back_accessory:'socket_back_accessory',vfx_origin:'socket_vfx_origin'},colliderHints:{torso:{type:'capsule',radius:.68,height:1.85},head:{type:'box',radius:.42},accessory:{type:'box',radius:.55}},performance:{},optimization:{strategy:'runtime-safe static decorations',mergeDeferred:true}};root.userData.sculptRuntime={pivots,sockets:root.userData.characterModel.sockets,colliderHints:root.userData.characterModel.colliderHints};root.traverse(o=>{if(o.isMesh){o.castShadow=options.castShadow??true;o.receiveShadow=options.receiveShadow??true;}});root.userData.characterModel.performance={...measureModelPerformance(root),lod0TriangleBudget:45000,mobileDrawCallBudget:24};return root;
}
export function createBaragaPlayableHeroLookDevLights(){const g=new THREE.Group();g.add(new THREE.HemisphereLight(0xd6c0a8,0x1a1311,1.55));const k=new THREE.DirectionalLight(0xffd09b,3.3);k.position.set(-4,6,5);g.add(k);const r=new THREE.DirectionalLight(0x6e87ad,1.5);r.position.set(4,3,-4);g.add(r);return g;}
