import * as THREE from '/vendor/three.module.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { createGeometryKit } from '../runtime/geometry_kit.js';
const { addMesh, addSocket, mergeStaticMeshesByMaterial, measureModelPerformance } = createGeometryKit(THREE, { mergeGeometries });
const mat = (color, opts = {}) => new THREE.MeshStandardMaterial({ color, roughness: .7, metalness: .12, ...opts });
const tube = (p, n, a, b, r, m, seg = 10) => { const s = new THREE.Vector3(...a), e = new THREE.Vector3(...b), d = e.clone().sub(s); const q = new THREE.Mesh(new THREE.CylinderGeometry(r, r * 1.1, d.length(), seg), m); q.name = n; q.position.copy(s).add(e).multiplyScalar(.5); q.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), d.normalize()); q.userData.staticDecoration = true; p.add(q); return q; };
export function createNuedoriPlayableHeroModel(options = {}) {
  const root = new THREE.Group(); root.name = 'nuedori_playable_hero'; root.userData.heroId = 'nuedori';
  const violet = mat(0x755b9c), ink = mat(0x241a35, { metalness: .42, roughness: .44 }); const silver = mat(0xb9a8d2, { metalness: .7, roughness: .25 }); const glow = mat(0xc9b4ff, { emissive: 0x6f3cc1, emissiveIntensity: 1.8 });
  const torso = new THREE.Group(); torso.name = 'pivot_torso'; torso.userData.semanticPivot = 'torso'; root.add(torso); torso.rotation.z = -.1;
  addMesh(torso, new THREE.CapsuleGeometry(.58, .92, 7, 14), ink, 'twisted_spine', [0, 1.85, 0]); addMesh(torso, new THREE.SphereGeometry(.68, 10, 8), violet, 'layered_torso_mantle', [0, 1.75, -.05], [0, 0, -.18]);
  const head = new THREE.Group(); head.name = 'pivot_head'; head.userData.semanticPivot = 'head'; root.add(head); head.position.set(.08, 3.08, .02); head.rotation.z = -.12;
  addMesh(head, new THREE.ConeGeometry(.48, .78, 5), ink, 'bird_mask', [0, 0, .08], [0, 0, 0]); addMesh(head, new THREE.ConeGeometry(.14, .7, 4), violet, 'offset_crest', [.3, .42, -.02], [0, 0, -.3]); addMesh(head, new THREE.ConeGeometry(.14, .38, 4), silver, 'mask_beak', [0, -.18, .48], [Math.PI / 2, 0, 0]); addMesh(head, new THREE.SphereGeometry(.06, 8, 6), glow, 'mask_eye', [-.18, .08, .42]);
  const pelvis = new THREE.Group(); pelvis.name = 'pivot_pelvis'; pelvis.userData.semanticPivot = 'pelvis'; root.add(pelvis); addMesh(pelvis, new THREE.SphereGeometry(.55, 10, 8), ink, 'coiled_pelvis', [0, .98, 0]);
  for (const side of ['left', 'right']) { const s = side === 'left' ? -1 : 1; const shoulder = new THREE.Group(); shoulder.name = `pivot_${side}_shoulder`; shoulder.userData.semanticPivot = `${side}Shoulder`; root.add(shoulder); shoulder.position.set(s * .56, 2.4, 0); addMesh(shoulder, new THREE.SphereGeometry(.29, 10, 8), violet, `${side}_asymmetric_shoulder`); const arm = new THREE.Group(); arm.name = `pivot_${side}_arm`; arm.userData.semanticPivot = `${side}Arm`; root.add(arm); tube(arm, `${side}_hooked_forearm`, [s * .6, 2.32, .04], [s * 1.0, 1.45, .34], .16, ink, 9); addMesh(arm, new THREE.ConeGeometry(.18, .48, 6), silver, `${side}_hook_claw`, [s * 1.03, 1.27, .4], [0, 0, s * .55]); const leg = new THREE.Group(); leg.name = `pivot_${side}_leg`; leg.userData.semanticPivot = `${side}Leg`; root.add(leg); tube(leg, `${side}_coiled_leg`, [s * .3, .9, 0], [s * .48, .24, .22], .2, violet, 9); for (let i = 0; i < 3; i++) tube(leg, `${side}_talon_${i}`, [s * (.48 + i * .07), .12, .2], [s * (.62 + i * .08), .08, .44], .035, silver, 6); }
  const mantle = new THREE.Group(); mantle.name = 'feather_mantle'; root.add(mantle); for (let i = 0; i < 7; i++) { const angle = (i - 3) * .28; addMesh(mantle, new THREE.ConeGeometry(.18, .72 + (i % 2) * .16, 5), violet, `mantle_feather_${i}`, [Math.sin(angle) * .72, 2.05 + Math.cos(angle) * .18, -.28 - Math.abs(angle) * .1], [angle * .7, 0, angle]); }
  const blade = new THREE.Group(); blade.name = 'hook_blade'; root.add(blade); tube(blade, 'hook_blade_grip', [1.05, 1.45, .34], [1.36, 1.22, .38], .065, silver, 8); addMesh(blade, new THREE.ConeGeometry(.18, .8, 5), silver, 'hook_blade_edge', [1.54, 1.0, .4], [0, 0, -Math.PI / 2]);
  const addS = (n, p) => addSocket(root, `socket_${n}`, p); addS('weapon_primary', [1.54, 1.0, .4]); addS('hand_off', [-1.0, 1.45, .34]); addS('back_accessory', [0, 2.15, -.55]); addS('vfx_origin', [.08, 3.12, .45]);
  const pivots = { root: root.name, head: head.name, torso: torso.name, pelvis: pelvis.name, leftShoulder: 'pivot_left_shoulder', rightShoulder: 'pivot_right_shoulder', leftArm: 'pivot_left_arm', rightArm: 'pivot_right_arm', leftLeg: 'pivot_left_leg', rightLeg: 'pivot_right_leg' }; const sockets = { weapon_primary: 'socket_weapon_primary', hand_off: 'socket_hand_off', back_accessory: 'socket_back_accessory', vfx_origin: 'socket_vfx_origin' }; const colliderHints = { torso: { type: 'capsule', radius: .66, height: 2.1 }, head: { type: 'sphere', radius: .5 }, accessory: { type: 'capsule', radius: .8, height: 1.4 } }; const optimization = Object.values(pivots).filter((n) => n !== root.name).map((n) => ({ pivot: n, ...mergeStaticMeshesByMaterial(root.getObjectByName(n)) })); root.userData.characterModel = { schemaVersion: '1.0.0', heroId: 'nuedori', implementation: 'handcrafted-img2threejs', coordinateSystem: 'three-y-up-front-positive-z', pivots, sockets, colliderHints, optimization: { strategy: 'per-pivot material merge', pivots: optimization }, performance: { ...measureModelPerformance(root), lod0TriangleBudget: 45000, mobileDrawCallBudget: 24 } }; root.userData.sculptRuntime = { pivots, sockets, colliderHints }; root.traverse((o) => { if (o.isMesh) { o.castShadow = options.castShadow ?? true; o.receiveShadow = options.receiveShadow ?? true; } }); return root;
}
export function createNuedoriPlayableHeroLookDevLights() { const g = new THREE.Group(); g.add(new THREE.HemisphereLight(0xd5c5ef, 0x171321, 1.5)); const key = new THREE.DirectionalLight(0xe2d3ff, 3); key.position.set(-4, 6, 5); g.add(key); const rim = new THREE.DirectionalLight(0x7654b5, 2); rim.position.set(3, 3, -5); g.add(rim); return g; }
