import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '/client/img2threejs/runtime/geometry_kit.js';
const { addMesh, addSocket, rebasePivot, measureModelPerformance } = createGeometryKit(THREE);
const M = {
  skin:new THREE.MeshStandardMaterial({color:0xd4a07e,roughness:.72}), hair:new THREE.MeshStandardMaterial({color:0x20183a,roughness:.5}), coat:new THREE.MeshStandardMaterial({color:0x713c9d,roughness:.62}), trim:new THREE.MeshStandardMaterial({color:0xe1b85c,metalness:.58,roughness:.3}), cloth:new THREE.MeshStandardMaterial({color:0x251a4b,roughness:.82}), cyan:new THREE.MeshStandardMaterial({color:0x50d9df,emissive:0x0b3944,emissiveIntensity:1.6,roughness:.24}), dark:new THREE.MeshStandardMaterial({color:0x151329,metalness:.35,roughness:.3})
};
const mesh=(p,g,m,n,pos,scale=[1,1,1])=>{const x=addMesh(p,g,m,n,pos);x.scale.set(...scale);return x;};
const tube=(p,n,a,b,r,m)=>{const A=new THREE.Vector3(...a), B=new THREE.Vector3(...b), d=B.clone().sub(A);const mid=A.clone().add(B).multiplyScalar(.5);const x=mesh(p,new THREE.CylinderGeometry(r,r,d.length(),8),m,n,[mid.x,mid.y,mid.z]);x.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return x;};
function pivot(root,key,pos){const p=new THREE.Group();p.name=`pivot_${key}`;p.userData.semanticPivot=key;root.add(p);root.updateMatrixWorld(true);rebasePivot(p,pos);return p;}
function create(){const root=new THREE.Group();root.name='shirabe_playable_hero';root.userData.heroId='shirabe';
 const torso=pivot(root,'torso',[0,2.05,0]); mesh(torso,new THREE.CapsuleGeometry(.48,.75,8,16),M.coat,'torso_resonant_coat',[0,2.1,0],[1.1,1,.72]); mesh(torso,new THREE.BoxGeometry(.62,.65,.12),M.trim,'torso_lute_panel',[0,2.25,.46],[1,1,.5]);
 const pelvis=pivot(root,'pelvis',[0,1.35,0]); mesh(pelvis,new THREE.SphereGeometry(.45,16,10),M.cloth,'pelvis_sash',[0,1.35,0],[1.12,.55,.85]);
 const head=pivot(root,'head',[0,3.0,0]); mesh(head,new THREE.SphereGeometry(.36,20,14),M.skin,'head_face',[0,3.06,.03],[.92,1.08,.9]); mesh(head,new THREE.SphereGeometry(.39,18,12),M.hair,'hair_bun',[0,3.28,-.04],[1.08,.72,.96]); mesh(head,new THREE.ConeGeometry(.11,.38,10),M.trim,'ear_ornament',[-.35,3.13,.02],[1,.8,1]); mesh(head,new THREE.SphereGeometry(.045,10,8),M.dark,'eye_l',[-.14,3.08,.32]); mesh(head,new THREE.SphereGeometry(.045,10,8),M.dark,'eye_r',[.14,3.08,.32]);
 const shL=pivot(root,'shoulder_l',[-.52,2.47,0]), shR=pivot(root,'shoulder_r',[.52,2.47,0]); mesh(shL,new THREE.SphereGeometry(.24,12,8),M.coat,'shoulder_l_shell',[-.52,2.47,0],[1,.8,.8]);mesh(shR,new THREE.SphereGeometry(.24,12,8),M.coat,'shoulder_r_shell',[.52,2.47,0],[1,.8,.8]);
 const armL=pivot(root,'arm_l',[-.68,2.18,0]),armR=pivot(root,'arm_r',[.68,2.18,0]); tube(armL,'arm_l_sleeve',[-.62,2.38,0],[-.84,1.75,.04],.14,M.coat);tube(armR,'arm_r_sleeve',[.62,2.38,0],[.84,1.75,.04],.14,M.coat);mesh(armL,new THREE.SphereGeometry(.14,10,8),M.skin,'hand_l',[-.84,1.68,.1]);mesh(armR,new THREE.SphereGeometry(.14,10,8),M.skin,'hand_r',[.84,1.68,.1]);
 const legL=pivot(root,'leg_l',[-.25,1.2,0]),legR=pivot(root,'leg_r',[.25,1.2,0]);tube(legL,'leg_l',[-.25,1.2,0],[-.3,.45,.06],.17,M.cloth);tube(legR,'leg_r',[.25,1.2,0],[.3,.45,.06],.17,M.cloth);mesh(legL,new THREE.SphereGeometry(.2,12,8),M.trim,'boot_l',[-.3,.2,.2],[1,.55,1.35]);mesh(legR,new THREE.SphereGeometry(.2,12,8),M.trim,'boot_r',[.3,.2,.2],[1,.55,1.35]);
 // Resonant musician silhouette: asymmetric wing-like soundboard and neck instrument.
 const lute=pivot(root,'lute',[.72,1.95,.28]);mesh(lute,new THREE.SphereGeometry(.34,18,12),M.trim,'lute_body',[0,0,0],[1.25,.82,.42]);tube(lute,'lute_neck',[0,.18,.02],[0,.95,.02],.055,M.dark);mesh(lute,new THREE.TorusGeometry(.11,.018,8,20),M.dark,'lute_soundhole',[0,.02,.18],[1,1,1]);addSocket(lute,'socket_weapon_primary',[0,.65,.1]);
 for(const s of [-1,1]){const wing=pivot(root,s<0?'wing_l':'wing_r',[s*.4,2.38,-.05]);for(let i=0;i<4;i++)mesh(wing,new THREE.ConeGeometry(.18,.8-i*.1,6),i%2?M.coat:M.cyan,`wing_${s<0?'l':'r'}_feather_${i}`,[s*(.66+i*.11),2.42-i*.15,-.12-i*.03],[.62,1,.24]);}
 addSocket(armL,'socket_hand_off',[0,0,.16]);addSocket(root,'socket_back_accessory',[0,2.48,-.36]);addSocket(root,'socket_vfx_origin',[0,2.1,.5]);
 const pivots={root:root.name,head:head.name,torso:torso.name,pelvis:pelvis.name,shoulder_l:shL.name,shoulder_r:shR.name,arm_l:armL.name,arm_r:armR.name,leg_l:legL.name,leg_r:legR.name,leftShoulder:shL.name,rightShoulder:shR.name,leftArm:armL.name,rightArm:armR.name,leftLeg:legL.name,rightLeg:legR.name};const sockets={weapon_primary:'socket_weapon_primary',hand_off:'socket_hand_off',back_accessory:'socket_back_accessory',vfx_origin:'socket_vfx_origin'};
 root.userData.characterModel={schemaVersion:'1.0.0',heroId:'shirabe',implementation:'handcrafted-img2threejs',coordinateSystem:'three-y-up-front-positive-z',pivots,sockets,colliderHints:{torso:{type:'capsule',radius:.55,height:1.7},head:{type:'sphere',radius:.37},height:3.5},performance:{...measureModelPerformance(root),lod0TriangleBudget:45000,mobileDrawCallBudget:24}};root.userData.sculptRuntime={pivots,sockets};root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return root;}
export function createShirabePlayableHeroModel(options={}){return create(options);}
