import * as THREE from '/vendor/three.module.js';
import { createGeometryKit } from '/client/img2threejs/runtime/geometry_kit.js';
const { addMesh, addSocket, mergeStaticMeshesByMaterial, measureModelPerformance } = createGeometryKit(THREE);
const mat = (color, metalness = .45, roughness = .4, emissive = 0) => new THREE.MeshStandardMaterial({ color, metalness, roughness, emissive, emissiveIntensity: emissive ? 2.2 : 0 });
const M = { orange: mat(0xef9d43, .6, .34), iron: mat(0x39434b, .82, .3), chain: mat(0xa8b0b5, .88, .22), dark: mat(0x171c22, .72, .42), glow: mat(0xff7b1a, .35, .2, 0xff3b00), cloth: mat(0x211c1b, .05, .9) };
function mesh(p, g, m, n, pos = [0,0,0], scale) { const x = addMesh(p, g, m, n, pos); if (scale) x.scale.fromArray(scale); return x; }
function limb(p, n, x, y, z, r, h, m) { return mesh(p, new THREE.CapsuleGeometry(r, h, 6, 10), m, n, [x,y,z]); }
function chain(p, x, y, z) { const g = new THREE.Group(); g.name = 'sternal_chain_spool'; p.add(g); mesh(g, new THREE.CylinderGeometry(.17,.17,.12,16), M.iron, 'chain_spool', [x,y,z], [1,1,.55]); for (let i=0;i<7;i++) { const a=i*.48; const link=mesh(g,new THREE.TorusGeometry(.1,.027,6,12),M.chain,`chain_link_${i}`,[x+.17*Math.sin(a),y-.14*i,z+.08*Math.cos(a)]); link.rotation.x=Math.PI/2; link.rotation.z=i%2?Math.PI/2:0; } return g; }
function anchor(p) { const g=new THREE.Group(); g.name='chain_anchor'; p.add(g); mesh(g,new THREE.CylinderGeometry(.09,.13,1.55,8),M.iron,'anchor_shaft',[0,-.75,0], [1,1,1]); mesh(g,new THREE.ConeGeometry(.25,.52,4),M.orange,'anchor_blade',[0,-1.72,0]); const ring=mesh(g,new THREE.TorusGeometry(.17,.05,8,16),M.chain,'anchor_ring',[0,.06,0]); ring.rotation.x=Math.PI/2; return g; }
export function createZairuPlayableHeroModel(options={}) {
 const root=new THREE.Group(); root.name='zairu_root';
 const pivots={root:root.name,head:'pivot_head',torso:'pivot_torso',pelvis:'pivot_pelvis',shoulder_l:'pivot_shoulder_l',shoulder_r:'pivot_shoulder_r',arm_l:'pivot_arm_l',arm_r:'pivot_arm_r',leg_l:'pivot_leg_l',leg_r:'pivot_leg_r',leftShoulder:'pivot_shoulder_l',rightShoulder:'pivot_shoulder_r',leftArm:'pivot_arm_l',rightArm:'pivot_arm_r',leftLeg:'pivot_leg_l',rightLeg:'pivot_leg_r'};
 const head=new THREE.Group(); head.name=pivots.head; head.userData.semanticPivot='head'; root.add(head);
 mesh(head,new THREE.SphereGeometry(.39,20,14),M.iron,'round_helm',[0,3.38,0]); mesh(head,new THREE.TorusGeometry(.34,.055,8,20),M.orange,'helm_rim',[0,3.35,.02]); mesh(head,new THREE.BoxGeometry(.18,.28,.16),M.dark,'chain_notch',[.27,3.18,0]); mesh(head,new THREE.BoxGeometry(.42,.06,.08),M.glow,'visor',[0,3.34,.34]);
 const torso=new THREE.Group(); torso.name=pivots.torso; torso.userData.semanticPivot='torso'; root.add(torso); mesh(torso,new THREE.CapsuleGeometry(.64,.72,8,12),M.iron,'barrel_chest',[0,2.3,0],[1.08,1,0.72]); mesh(torso,new THREE.BoxGeometry(1.02,.11,.1),M.orange,'anchor_harness',[0,2.48,.53]); mesh(torso,new THREE.BoxGeometry(.1,.62,.08),M.orange,'harness_strap',[-.3,2.28,.54]); mesh(torso,new THREE.BoxGeometry(.1,.62,.08),M.orange,'harness_strap',[.3,2.28,.54]); chain(torso,0,2.15,.55);
 const pelvis=new THREE.Group(); pelvis.name=pivots.pelvis; pelvis.userData.semanticPivot='pelvis'; root.add(pelvis); mesh(pelvis,new THREE.BoxGeometry(.98,.34,.62),M.dark,'pelvis_armor',[0,1.63,0]); mesh(pelvis,new THREE.BoxGeometry(.42,.38,.07),M.orange,'waist_tab',[0,1.62,.36]);
 for (const side of [-1,1]) { const s=side<0?'l':'r'; const shoulder=new THREE.Group(); shoulder.name=pivots[`shoulder_${s}`]; shoulder.userData.semanticPivot=`shoulder_${s}`; root.add(shoulder); mesh(shoulder,new THREE.SphereGeometry(.3,14,10),M.orange,`shoulder_${s}_plate`,[side*.72,2.65,0],[1,.72,1.05]); const arm=new THREE.Group(); arm.name=pivots[`arm_${s}`]; arm.userData.semanticPivot=`arm_${s}`; root.add(arm); limb(arm,`upper_arm_${s}`,side*.78,2.25,0,.18,.42,M.iron); limb(arm,`weighted_gauntlet_${s}`,side*.8,1.78,.04,.23,.34,M.dark); mesh(arm,new THREE.SphereGeometry(.22,12,8),M.orange,`gauntlet_weight_${s}`,[side*.8,1.6,.05]); const leg=new THREE.Group(); leg.name=pivots[`leg_${s}`]; leg.userData.semanticPivot=`leg_${s}`; root.add(leg); limb(leg,`thigh_${s}`,side*.32,1.16,0,.25,.48,M.iron); limb(leg,`greave_${s}`,side*.32,.55,.02,.22,.55,M.dark); mesh(leg,new THREE.BoxGeometry(.42,.18,.7),M.iron,`boot_${s}`,[side*.32,.16,.14]); }
 const weapon=addSocket(root,'socket_weapon_primary',[.95,1.78,.05]); const off=addSocket(root,'socket_hand_off',[-.85,1.72,.05]); const back=addSocket(root,'socket_back_accessory',[0,2.35,-.48]); const vfx=addSocket(root,'socket_vfx_origin',[0,2.55,.65]);
 const w=new THREE.Group(); w.name='weapon_chain_anchor'; weapon.add(w); w.rotation.z=-.28; mesh(w,new THREE.CylinderGeometry(.07,.09,1.05,10),M.iron,'anchor_handle',[0,-.52,0]); mesh(w,new THREE.ConeGeometry(.2,.45,4),M.orange,'anchor_head',[0,-1.18,0]);
 for(let i=0;i<5;i++){const l=mesh(w,new THREE.TorusGeometry(.09,.025,6,12),M.chain,`weapon_chain_${i}`,[0,-1.45-.22*i,0]); l.rotation.x=i%2?Math.PI/2:0;} anchor(off);
 const cape=mesh(back,new THREE.ConeGeometry(.48,1.15,5,1,true),M.cloth,'anchor_cape',[0,-.55,0],[1,1,.18]); cape.rotation.x=Math.PI;
 root.userData.characterModel={schemaVersion:'1.0.0',heroId:'zairu',implementation:'handcrafted-img2threejs',coordinateSystem:'three-y-up-front-positive-z',pivots,sockets:{weapon_primary:'socket_weapon_primary',hand_off:'socket_hand_off',back_accessory:'socket_back_accessory',vfx_origin:'socket_vfx_origin'},colliderHints:{torso:{type:'capsule',radius:.62,height:1.7},head:{type:'sphere',radius:.4},accessory:{type:'box',radius:.6}},performance:{}};
 root.userData.sculptRuntime={pivots,sockets:root.userData.characterModel.sockets,colliderHints:root.userData.characterModel.colliderHints};
 // The browser runtime may not bundle BufferGeometryUtils; leave static nodes intact
 // when the kit has no merger rather than throwing during factory construction.
 root.userData.characterModel.optimization={strategy:'runtime-safe static decorations',mergeDeferred:true};
 root.traverse(o=>{if(o.isMesh){o.castShadow=options.castShadow??true;o.receiveShadow=options.receiveShadow??true;}}); root.userData.characterModel.performance={...measureModelPerformance(root),lod0TriangleBudget:45000,mobileDrawCallBudget:24}; return root;
}
export function createZairuPlayableHeroLookDevLights(){const g=new THREE.Group();g.add(new THREE.HemisphereLight(0xb7d7e2,0x18202a,1.5));const k=new THREE.DirectionalLight(0xffd2a0,3);k.position.set(-3,6,5);g.add(k);const r=new THREE.DirectionalLight(0x4e78aa,1.6);r.position.set(3,3,-4);g.add(r);return g;}
